name: Floatplane-App Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - name: Build and Test Models
        run:  xcodebuild test -project FloatplaneApp-App/FloatplaneApp.xcodeproj -scheme FloatplaneApp-Models -destination 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=16.1' build test
      - name: Build and Test Utilities
        run:  xcodebuild test -project FloatplaneApp-App/FloatplaneApp.xcodeproj -scheme FloatplaneApp-Utilities -destination 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=16.1' build test
      - name: Build and Test DataStores
        run:  xcodebuild test -project FloatplaneApp-App/FloatplaneApp.xcodeproj -scheme FloatplaneApp-DataStores -destination 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=16.1' build test
      - name: Build and Test Operations
        run:  xcodebuild test -project FloatplaneApp-App/FloatplaneApp.xcodeproj -scheme FloatplaneApp-Operations -destination 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=16.1' build test
      - name: Build App
        run:  xcodebuild test -project FloatplaneApp-App/FloatplaneApp.xcodeproj -scheme FloatplaneApp -destination 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=16.1' build test
        

